### PR TITLE
Performance improvement.

### PR DESCRIPTION
**Pull request by ckeleshi**

### CODE REVIEW

**Comment by ThirteenAG** [comment]
Wanted to test today, but couldn't. Will try tomorrow.

**Comment by ThirteenAG** [comment]
Briefly tested it, so far so good.

**Comment by ThirteenAG** [comment]
There's been a report that Splinter Cell 3 stopped working.
Everything good up until that point: https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/source/SplinterCellChaosTheory.WidescreenFix/dllmain.cpp#L171

Then this becomes an infinite loop:
https://github.com/ThirteenAG/Hooking.Patterns/blob/master/Hooking.Patterns.cpp#L90

**Comment by ThirteenAG** [comment]
I also noticed that the created pattern string is "D9 05 BC B6 20 11 ", with the extra space at the end. Maybe that's why such behavior occurs.

**Comment by ThirteenAG** [comment]
So, without these hooks: https://github.com/ThirteenAG/WidescreenFixesPack/blob/master/source/SplinterCellChaosTheory.WidescreenFix/dllmain.cpp#L170-L178
it works. Seems like patterns with std::string as a parameter cause this.

**Comment by ThirteenAG** [comment]
I was able to do some tests, my initial assumption was correct, if pattern string ends with space, it hangs.
It works fine that way:
```
    const char *patend = (pattern + strlen(pattern) + 1);
    while (*(patend - 2) == ' ')
        patend--;
```
@ClansChen thoughts?

**Comment by ckeleshi** [comment]
I'm sorry. The first case (!temp_string[0] && !temp_string[1]) does not increase patit.

**Comment by ThirteenAG** [comment]
@ClansChen Will you pull request a fix also?

**Pull request merged**
