### PR TITLE
Half wildcard.

### PR DESCRIPTION
**Pull request by ckeleshi**

### CODE REVIEW

**Comment by CookiePLMonster** [comment]
What's the use case for matching nibbles?

**Comment by ckeleshi** [comment]
Ha, not found yet. May be for asm instructions having same names but different registers.

**Comment by ThirteenAG** [comment]
What about compatibility? Are there any regressions in speed or functionality?

**Comment by ckeleshi** [comment]
It's 100% compatible with original syntax. Check readme in my pr.
About 25% slower.

**Comment by CookiePLMonster** [comment]
`for_each_result` should probably call `EnsureMatches(UINT32_MAX)` before invoking the loop - or else constructs like

```pattern("XX XX XX XX").for_each_result( XXX );```

will not work as expected. Thus, it must lose its `const` qualifier.

**Comment by ckeleshi** [comment]
Oh, forgot its laziness. What about being hungry?

**Comment by ThirteenAG** [comment]
@ClansChen So, I got a chance to test it and I'm quite disappointed.
I tried to run currently under development fix for Driv3r, with old version(I believe commit ae4c807ca631928ae388b1362f80bd864f7faed7) it takes 2 seconds for all code to execute(in debug mode):
devenv_2017-06-29_12-27-46
And after I did submodule update, the results aren't quite as good:
devenv_2017-06-29_12-27-12

**Comment by CookiePLMonster** [comment]
You could probably simplify half-patterns a lot by making them a mask. This
way the current algorithm to find patterns would be left unchanged - only
with the values being masked with FF (value), F0 or 0F (half wildcard) or
00 (full wildcard).

2017-06-29 11:31 GMT+02:00 Sergey P. <notifications@github.com>:

**Comment by ckeleshi** [comment]
How's in Release build?

**Comment by ThirteenAG** [comment]
I didn't measure it specifically, but I think about the same as it was. Game starts pretty quick.

**Comment by ckeleshi** [comment]
I will remove operator[] calls in searching and see how it will be.

**Comment by ThirteenAG** [comment]
@ClansChen Any progress?

**Pull request merged**
